# Generated by Django 4.1 on 2023-03-19 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(help_text='Enter a company name.', max_length=100)),
                ('estb', models.DateField(help_text='Enter date of establishment.')),
                ('company_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('nutrient_set_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('calories', models.IntegerField(help_text='Enter calories amount.')),
                ('protein', models.IntegerField(help_text='Enter protein amount.')),
                ('fibre', models.IntegerField(help_text='Enter fibre amount.')),
                ('fat', models.IntegerField(help_text='Enter fat amount.')),
                ('sugar', models.IntegerField(help_text='Enter sugar amount.')),
                ('carbohydrates', models.IntegerField(help_text='Enter carbohydrates amount.')),
            ],
        ),
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('chocolate_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular chocolate.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter chocolate name.', max_length=100)),
                ('price', models.IntegerField(help_text='Enter Price.')),
                ('chocolate_type', models.CharField(help_text='Enter type of chocolate.', max_length=50)),
                ('decription', models.TextField()),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.company')),
                ('nutrients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.nutrients')),
            ],
        ),
    ]
